---
# SPDX-License-Identifier: GPL-3.0-or-later
# (c) 2020-2024 Peter Mosmans [Go Forward]
#
# Executes SonarScanner and uploads results to SonarQube.
#
# Variables:
# SONAR_TOKEN        SonarQube access token
# SONAR_URL          Location of SonarQube
# TOOLS_VERSION      Specifies which version of gofwd/tools-image is being used

sonarqube:
  extends: .sast
  variables:
    GIT_DEPTH: 1
    GIT_STRATEGY: fetch
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  image:
    name: gofwd/tools-image:${TOOLS_VERSION}
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - >
      sonar-scanner
      -Dsonar.exclusions=reports/**
      -Dsonar.host.url=${SONAR_URL}
      -Dsonar.path.temp=${RUNNER_TEMP_PROJECT_DIR}
      -Dsonar.projectKey=${CI_PROJECT_TITLE}
  rules:
    - if: "$SONAR_TOKEN != null"
      when: always
